name: Install fresh packages

on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: |

       npm install
       cmd
       git config --global user.name "19srzhu"
       git config --global user.email "%19srzhu_email_address%"
       git add .
       git commit -m"Updated packages"
       git push
    env:
      19srzhu_email_address: ${{ secrets.octocat }}
