name: Node.js CI

on:
  workflow_dispatch:
  schedule:
    - cron: "30 0,6,12,18 * * *"
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use latest Node.js version
      uses: actions/setup-node@v2.1.2
      with:
        node-version: "15.0.1"
    - run: node .
    env:
      Discord_Bot_Token: ${{ secrets.Discord_Bot_Token }}
      Discord_Restart_Webhook_Token: ${{ secrets.Discord_Restart_Webhook_Token }}
